import Head from "next/head";
import { appName } from "@/configs/app";
import Layout from "@/components/dasboard-layout";
import HomeContainer from "@/components/dashboard/home-container";
import { NextPageWithLayout } from "../_app";
import { RequireAuth } from "@/components/auth/RequireAuth";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Mezcal Artesanal {appName} ® &#8211; {appName}</title>
        <meta
          name="title"
          content={`Mezcal Artesanal ${appName} ® &#8211; ${appName}`}
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer />
    </>
  );
}

Home.getLayout = (page)=>{
  return <RequireAuth>
    <Layout>
      {page}
    </Layout>
  </RequireAuth>
}

export default Home
