import Layout from "@/components/layout";
import LoginForm from "@/components/login";
import { appName } from "@/configs/app";
import Head from "next/head";

export default function Login() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta
          name="title"
          content={`Mezcal Artesanal ${appName} ® &#8211; ${appName}`}
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Volver a la tienda" hideBrandLogo hideBottomNav showBackButton backTo="/">
        <div className="w-100 flex-grow-1 d-flex align-items-center justify-content-center p-3">
          <LoginForm />
        </div>
      </Layout>
    </>
  );
}
