import CheckoutComponent from "@/components/checkout";
import Layout from "@/components/layout";
import Head from "next/head";
import { appName } from "@/configs/app";

export default function CheckoutView() {
  return (
    <>
      <Head>
        <title>Realiza tu pago</title>
        <meta
          name="title"
          content={`Mezcal Artesanal ${appName} ® &#8211; ${appName}`}
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <CheckoutComponent />
      </Layout>
    </>
  );
}
