import CheckoutForm from "@/components/checkout-form";
import Layout from "@/components/layout";
import { appName } from "@/configs/app";
import Head from "next/head";

export default function PaymentDataView() {
  return (
    <>
      <Head>
        <title>Ingresa los datos de facturación</title>
        <meta
          name="title"
          content={`Mezcal Artesanal ${appName} ® &#8211; ${appName}`}
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title={appName} hideBrandLogo>
        <CheckoutForm />
      </Layout>
    </>
  );
}
